# Generated by Django 5.2.11 on 2026-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hero_statement', models.TextField(help_text='A brief catchy statement')),
                ('about_me', models.TextField()),
                ('profile_image', models.ImageField(upload_to='projects/')),
                ('skills', models.JSONField(default=list, help_text='List of skills')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technologies', models.TextField()),
                ('solution', models.TextField(help_text='Detailed solution description')),
                ('challenges', models.TextField(help_text='Challenges faced during the project')),
                ('project_image', models.ImageField(upload_to='projects/')),
                ('live_link', models.URLField(blank=True, null=True)),
                ('repo_link', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
