# Generated by Django 5.2.9 on 2026-02-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_contactinfo_message_delete_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.JSONField(default=dict, help_text='Skills organized by category. Format: {"Frontend": ["React", "JavaScript"], "Backend": ["Python", "Django"], "Tools": ["Git", "Docker"]}'),
        ),
    ]
