# Generated by Django 5.2.11 on 2026-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Full Stack Software Engineer', help_text='Professional title or tagline', max_length=255),
        ),
    ]
