# Generated by Django 5.2.11 on 2026-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
